In [18]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/twitter-likes-prediction-famous/sample_submission.csv
/kaggle/input/twitter-likes-prediction-famous/train.csv
/kaggle/input/twitter-likes-prediction-famous/test.csv

In [19]:
train=pd.read_csv('/kaggle/input/twitter-likes-prediction-famous/train.csv')
test=pd.read_csv('/kaggle/input/twitter-likes-prediction-famous/test.csv')
sub=pd.read_csv('/kaggle/input/twitter-likes-prediction-famous/sample_submission.csv')

In [20]:
train

          keyword  likes                                             tweets
0        COVID-19      1  The headline kinda makes it sound like the AP ...
1        COVID-19      0  ATLANTIC CITY — The city's Police Athletic Lea...
2        COVID-19      0  I feel like Diana's line she draws is if his s...
3        COVID-19      1  COVID-19 was the single most fatal communicabl...
4        COVID-19      0  Studies: Dogs can detect COVID-19 with greater...
...           ...    ...                                                ...
128832  World Cup      1       He is in Argentina to play the U20 World Cup
128833  World Cup      0  Messi this season in every competition 60g/a w...
128834  World Cup     29  🚨#2026WCQ 54 African countries will be divided...
128835  World Cup      0  England’s adopted World Cup mascot ‘Dave the C...
128836  World Cup      0  End kartay hain us ne apnay Country ko Fifa Wo...

[128837 rows x 3 columns]

In [21]:
import pandas as pd

# Assuming your original DataFrame is named 'original_df'

# Set the random seed for reproducibility (optional)
random_seed = 42
pd.np.random.seed(random_seed)

# Select 2000 random rows from the original DataFrame
sampled_df = train.sample(n=2000)

# Create a new DataFrame from the sampled rows
new_df = pd.DataFrame(sampled_df)

# Reset the index of the new DataFrame
new_df.reset_index(drop=True, inplace=True)

/tmp/ipykernel_33/569557536.py:7: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.
  pd.np.random.seed(random_seed)

In [22]:
train=new_df

In [23]:
train

             keyword  likes                                             tweets
0                nba      1  We’re supposed to ignore Durant &amp; Westbroo...
1            Ukraine      0               QUIT GIVING ALL THE MONEY TO UKRAINE
2            YouTube      0                              Your YouTube videos 🔥
3                NFT      1  The growth of the #NFT market is undeniable, a...
4        Johnny Depp      0  Have you seen the movie Ringo where Johnny Dep...
...              ...    ...                                                ...
1995        Olympics     12  8 olympic golds, 1 silver and 1 bronze are a t...
1996        COVID-19     10  MURDER ON THE RUBY PRINCESS 04.08.2020 by THEB...
1997  Jeffrey Dahmer      1  So much bullshit around this new process to ev...
1998         Bitcoin      0  i dont know why you leftists use "crypto bro" ...
1999      Super Bowl      1                         STILLERS GHANTA SUPER BOWL

[2000 rows x 3 columns]

In [24]:
test

        id   keyword                                              tweet
0        1  COVID-19  The first idiot was leaving space for an Eleph...
1        2  COVID-19  Do you have any suggestions? How can we improv...
2        3  COVID-19  Amazing from outside , but it has blood stain ...
3        4  COVID-19     I'm tryin to black out into the new year 💁🏻‍♂️
4        5  COVID-19  Yes it is ... and Kabir Sahab is right .. we s...
...    ...       ...                                                ...
9339  9340     apple  Apple offers replacement iPhone batteries effe...
9340  9341     apple  #BaconDay #Caramelized #Bacon  #Apple #Coffeec...
9341  9342     apple  I want my money back. I bought the  cd and it ...
9342  9343     apple  Apple Apologizes for Secretly Slowing Older iP...
9343  9344     apple  I have a Dell XPS 13 9650 also (I have too man...

[9344 rows x 3 columns]

In [25]:
sub

        id  likes
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0
...    ...    ...
9339  9340      0
9340  9341      0
9341  9342      0
9342  9343      0
9343  9344      0

[9344 rows x 2 columns]

In [26]:
X=train['tweets']
y=train['likes']

test=test['tweet']

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

# Tokenize the questions
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(X)

test=vectorizer.transform(test)

In [28]:
X.shape

(2000, 8707)

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [30]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_squared_error

# Instantiate the models
rf_reg = RandomForestRegressor(random_state=42,verbose =2)
# gb_reg = GradientBoostingRegressor(random_state=42)
# cat_reg = CatBoostRegressor(random_state=42, verbose=0)

# Train the models
rf_reg.fit(X_train, y_train)
# gb_reg.fit(X_train, y_train)
# cat_reg.fit(X_train, y_train)

# Make predictions on the test set
rf_pred = rf_reg.predict(X_test)
# gb_pred = gb_reg.predict(X_test)
# cat_pred = cat_reg.predict(X_test)

# Calculate the mean squared error for each model
rf_mse = mean_squared_error(y_test, rf_pred)
# gb_mse = mean_squared_error(y_test, gb_pred)
# cat_mse = mean_squared_error(y_test, cat_pred)

print("Random Forest Regressor MSE: {:.4f}".format(rf_mse))
# print("Gradient Boosting Regressor MSE: {:.4f}".format(gb_mse))
# print("CatBoost Regressor MSE: {:.4f}".format(cat_mse))

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.

building tree 1 of 100

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.6s remaining:    0.0s

building tree 2 of 100
building tree 3 of 100
building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100
building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70 of 100
building tree 71 of 100
building tree 72 of 100
building tree 73 of 100
building tree 74 of 100
building tree 75 of 100
building tree 76 of 100
building tree 77 of 100
building tree 78 of 100
building tree 79 of 100
building tree 80 of 100
building tree 81 of 100
building tree 82 of 100
building tree 83 of 100
building tree 84 of 100
building tree 85 of 100
building tree 86 of 100
building tree 87 of 100
building tree 88 of 100
building tree 89 of 100
building tree 90 of 100
building tree 91 of 100
building tree 92 of 100
building tree 93 of 100
building tree 94 of 100
building tree 95 of 100
building tree 96 of 100
building tree 97 of 100
building tree 98 of 100
building tree 99 of 100
building tree 100 of 100
Random Forest Regressor MSE: 6928.0027

[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:   50.8s finished
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 100 out of 100 | elapsed:    0.0s finished

In [15]:
y_pred=rf_reg.predict(test)

In [31]:
import joblib

# Save the pre-trained model
joblib.dump(rf_reg, 'twitter_prediction.pkl')

# Save the CountVectorizer
joblib.dump(vectorizer, 'vectorizer.pkl')

['twitter_prediction.pkl']

In [32]:
df=pd.read_csv('/kaggle/input/twitter-likes-prediction-famous/test.csv')
df['likes']=y_pred.astype(int)
od=df[['id','likes']]
od

        id  likes
0        1      6
1        2      3
2        3      5
3        4      3
4        5      2
...    ...    ...
9339  9340      2
9340  9341      2
9341  9342      2
9342  9343      2
9343  9344      5

[9344 rows x 2 columns]

In [33]:
od.to_csv('submission_twli4.csv',index=False)